image: Visual Studio 2019

install:
  - gitversion /l console /output buildserver

configuration:
  - Release

dotnet_csproj:
  patch: true
  version: '$(GitVersion_SemVer)'

build_script:
  - dotnet build

test_script:
  - dotnet test

after_test:
  - dotnet pack

artifacts:
  - path: 'nupkg\*.nupkg'